---
# tasks file for roles/common
- name: Update the packages
   ansible.builtin.apt:
       name: "*"
       state: latest
       update_cache: yes
- name: Install the common packages
         ansible.builtin.apt:
              pkg: "{{ common_packages }}"
              state: present
