vault_slack_webhook_url: "https://hooks.slack.com/services/T000/B000/XXXX"
vault_grafana_admin_password: "MySuperSecurePassword123"
vault_aws_access_key: "AKIAXXXXXXXXXXXXXXXX"
vault_aws_secret_key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
